# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'bweather' do
  pod 'ASIHTTPRequest', '~> 1.8.2'
  pod 'FMDB', '~> 2.5'
end

target 'bweatherTests' do

end

